# Generated by Django 3.2.7 on 2021-09-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('last_name2', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('document_id', models.CharField(max_length=255, unique=True, verbose_name='Cédula')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(max_length=50, verbose_name='Género')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('id_employee', models.CharField(max_length=255, unique=True, verbose_name='Nùmero de empleado')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('leader', models.CharField(max_length=50, verbose_name='Jefe')),
                ('zone', models.CharField(max_length=50, verbose_name='Zona')),
                ('city', models.CharField(max_length=50, verbose_name='Municipio')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo elèctronico')),
                ('image', models.URLField(verbose_name='Imagen')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
    ]
